### ISSUE TITLE
The datasets and notebooks are not matching

### ISSUE THREAD

**Issue by WhiteWolf82** [ServiceNow/insight-bench#1]
Hi, thank you for your efforts for constructing a benchmark for LLM-based data analysis!

I'm trying to run our project on your benchmark, but found that many notebooks and csv files are not correctly matched.

For example, in notebook 'flag-32.ipynb', the goal is to "investigate the extended durations of 'Cost Reduction' goals within the Finance department". But in the corresponding csv file 'csvs/flag-32.csv', there's not a 'department' field, which makes it impossible to complete the analysis goal. Moreover, the dataset loading cell in 'flag-32.ipynb' also mismatches the claimed 'csvs/flag-32.csv' file.

Can you fix that and double-check all notebook-csv matches? Thank you in advance!

**Comment by WhiteWolf82** [comment]
Here is the notebook 'flag-32.ipynb':
<img width="1083" alt="image" src="https://github.com/user-attachments/assets/e83b6635-d115-43b5-b513-56312d446cdf">

And here is the csv file 'flag-32.csv':
<img width="1256" alt="image" src="https://github.com/user-attachments/assets/0c2b409f-93db-48d8-9218-81520a939d0d">

It's clear that the loaded file does not match with the csv file path.

**Comment by IssamLaradji** [comment]
Thanks for your interest in evaluating using this dataset, and I appreciate you pointing this out @WhiteWolf82. 

We have noticed that we accidentally have some of the csvs overriden with a version that doesn't work with their corresponding notebooks. We will look into it today and update this benchmark with a fix. 

We will also add a unit test to make sure this won't happen again.

**Comment by IssamLaradji** [comment]
@WhiteWolf82 ,. we’ve fixed all the CSV files, added unit tests, and included JSON files to make loading the datasets easier.

We also added a basic script to help you evaluate your model. You can see how to use it in the README and as shown below.

Thanks for pointing out the issue—hope this helps, and please let us know if there is anything else we can do to help you with the evaluation!

```
import os
from insightbench import benchmarks, agents

# Set OpenAI API Key
# os.environ["OPENAI_API_KEY"] = "<openai_api_key>"


# Get Dataset
dataset_dict = benchmarks.load_dataset_dict("data/notebooks/flag-1.json")

# Run an Agent
agent = agents.Agent(
    model_name="gpt-4o-mini",
    max_questions=2,
    branch_depth=1,
    n_retries=2,
    savedir="results/sample",
)
pred_insights, pred_summary = agent.get_insights(
    dataset_csv_path=dataset_dict["dataset_csv_path"], return_summary=True
)


# Evaluate
score_insights = benchmarks.evaluate_insights(
    pred_insights=pred_insights,
    gt_insights=dataset_dict["insights"],
    score_name="rouge1",
)
score_summary = benchmarks.evaluate_summary(
    pred=pred_summary, gt=dataset_dict["summary"], score_name="rouge1"
)

# Print Score
print("score_insights: ", score_insights)
print("score_summary: ", score_summary)
```

**Comment by WhiteWolf82** [comment]
@IssamLaradji Thank you for your instant feedback and quick fix! This does help a lot for our evaluation.
